### ISSUE TITLE
Questions For Client (Week  2)

### ISSUE THREAD

**Issue by ShadeRemix** [LawJunHao/ICT2201-Team-Project-T8#4]
What to ask the prof

**Comment by LawJunHao** [comment]
Check Job preference should be at which page (Landing page?)

**Comment by edwin3746** [comment]
What credentials do you require specifically like ID or Worker pass

**Comment by edwin3746** [comment]
Is there a need for availability viewing and scheduling for the manager? In case the current manager is unable to be on duty

**Comment by Excelic** [comment]
Does the manager have access to feature such adding, deleting or editing a task.

**Comment by Excelic** [comment]
Does staff have the ability to view which shift was taken by others when they are trying to book their shift?

**Comment by LawJunHao** [comment]
Final questions that will be asked:
1) When a staff gets a warning from rejecting assigned jobs, are the managers able to track how many times they were introduced? 
2) Is there are way to verify that the staff has discussed with the manage for the approval of task rejection, like some sort of 2FA to approve the rejection or like a signature requirement from the manager to let the rejection go through. For now we just put it inisde a seperate page for the manager to tick yes or no only for the cases. 
3) In addition to the top 3 underassigned and overassigned staff to be shown, do you want an expansion list, in descending/ascending order for the other staff that are not in the top 3? Because there might be more than 50 staff overassigned but the manager doesn't know caus they only show top 3. 
4) Check Job preference should be at which page (Landing page? Seperate page?)
5) What credentials (for user login) do you require, specifically like unique ID?, worker ID?, work email? or personal email. 
6) Is there a need for availability viewing and scheduling for the manager? In case the current manager is unable to be on duty. Is there a fix shift for managers and we dont need to worry about their schedule? If managers have their own schedule who plans  for them? do they do their own planning?
7) Does the manager have access to feature such adding, deleting or editing the job allocation.
8) Does staff have the ability to view which shift was taken by others when they are trying to book their shift?

Additional qns: 
1) What preferred language does the client have for the app? 
2) When do you want to view the prototype by?
3) Is the current colour scheme proposed suitable for the app? 
4)
