### ISSUE TITLE
What could be improved?

### ISSUE THREAD

**Issue by ShadeRemix** [LawJunHao/ICT2201-Team-Project-T8#77]
Provide what are the areas for improvement for M2, collate and summarise the points that everyone contributed.

**Comment by LawJunHao** [comment]
Knowing that the deadline was shorter than what was given for M1, we should have planned the deadlines less packed towards the end. Because of the timeline we planned for completition of certain parts of the M2 reports, unecessary amount of stress was put on all of us towards the end of the submission timing. This was caused by sudden issues and changes to our solution proposed, thus leading to more than usual crunch hours

**Comment by edwin3746** [comment]
We could have researched and compared the different architecture and design patterns to find the best suitable pattern for our project. However, this area of improvement is caused due to time constraints and the effort expanded on multiple changes to our design.

**Comment by LawJunHao** [comment]
Project board numbering didn't go as well as planned initially. We lacked syncing between our work Breakdown structure and the tasks listed in the github board
